/**
 * NXTED AI — Master SEO Keyword Map
 * 150+ targeted keywords organized by intent and page.
 * Updated for 2026 AI career platform search landscape.
 */

// ─── Primary Keywords (High Volume, High Intent) ────────
export const PRIMARY_KEYWORDS = [
  'AI resume builder',
  'AI career coach',
  'AI job matching',
  'AI skill assessment',
  'AI career platform',
  'AI job search tool',
  'ATS friendly resume builder',
  'AI career planning',
  'automated job application',
  'AI interview preparation',
  'career development AI',
  'AI powered resume writer',
  'job search automation',
  'AI career copilot',
  'skill gap analysis AI',
] as const;

// ─── Long-Tail Keywords (Lower Competition, Higher Conversion) ──
export const LONG_TAIL_KEYWORDS = [
  'free AI resume builder online',
  'AI resume builder with ATS optimization',
  'best AI tool for job seekers 2026',
  'AI career coach for career changers',
  'AI skill assessment test free',
  'personalized career plan generator AI',
  'AI job matching based on skills',
  'automated job applications AI tool',
  'AI cover letter generator free',
  'AI resume scorer and optimizer',
  'career path recommendation AI',
  'AI interview practice tool',
  'portfolio builder for tech jobs',
  'AI resume tailor for job description',
  'how to use AI for job search',
  'AI career transition planner',
  'machine learning job matching',
  'AI resume keyword optimizer',
  'best AI career development platform',
  'AI job application tracker',
  'adaptive learning path AI',
  'AI proof of skills verification',
  'market readiness score AI',
  'hire probability calculator AI',
  'AI career operating system',
  'full stack career platform AI',
  'AI resume builder for engineers',
  'AI career coach for data scientists',
  'AI job search assistant 2026',
  'resume builder with AI suggestions',
  'AI skill test for developers',
  'career roadmap generator AI',
  'AI linkedin profile optimizer',
  'automated resume tailoring AI',
  'AI mock interview with feedback',
] as const;

// ─── Page-Specific SEO Configurations ──────────────────
export const PAGE_SEO = {
  home: {
    title: 'NXTED AI — Free AI Resume Builder, Career Coach & Job Matching Platform',
    description: 'NXTED AI is the #1 AI career platform. Free AI resume builder, personalized career coaching, skill assessment, adaptive learning paths, and AI-powered job matching. Start your career transformation today.',
    keywords: 'AI resume builder, AI career coach, AI job matching, free AI career platform, ATS resume builder, skill assessment AI, career development tool, job search automation, AI career copilot, personalized career plan',
    canonical: '/',
    h1: 'Your AI Career Operating System — From Skill Assessment to Dream Job',
  },
  pricing: {
    title: 'NXTED AI Pricing — Free AI Resume Builder & Career Tools | Plans from $0',
    description: 'Start free with AI resume builder, skill assessments, and career coaching. Pro plan at $19/mo for unlimited features. Ultra at $49/mo with automated job applications. Student discounts available.',
    keywords: 'AI resume builder pricing, AI career tool cost, free career platform, cheap AI resume builder, AI job search tool pricing, career coaching plans, resume builder subscription',
    canonical: '/pricing',
    h1: 'Simple, Transparent Pricing for AI Career Tools',
  },
  about: {
    title: 'About NXTED AI — AI-Powered Career Development Platform by OFORO AI',
    description: 'NXTED AI by OFORO AI is reimagining career development with artificial intelligence. Our AI career coach, resume builder, and job matching system help thousands land their dream jobs.',
    keywords: 'about NXTED AI, OFORO AI, AI career development company, AI job platform team, career technology startup',
    canonical: '/about',
    h1: 'Reimagining Career Development with AI',
  },
  security: {
    title: 'Security & Privacy — NXTED AI | Your Career Data Protected',
    description: 'NXTED AI protects your career data with enterprise-grade encryption, GDPR compliance, PII redaction, and SOC 2 ready infrastructure. Your privacy is our priority.',
    keywords: 'NXTED AI security, career data privacy, GDPR compliant career platform, secure resume builder, encrypted career data',
    canonical: '/security',
    h1: 'Enterprise-Grade Security for Your Career Data',
  },
  login: {
    title: 'Sign In to NXTED AI — AI Resume Builder & Career Dashboard',
    description: 'Sign in to your NXTED AI account to access your AI career coach, resume builder, skill assessments, career plan, and job matching dashboard.',
    keywords: 'NXTED AI login, career platform sign in, AI resume builder login',
    canonical: '/login',
    h1: 'Welcome Back to NXTED AI',
  },
  signup: {
    title: 'Create Free Account — NXTED AI | AI Resume Builder & Career Coach',
    description: 'Sign up free for NXTED AI. Get instant access to AI resume builder, skill assessment, personalized career plan, and AI career coaching. No credit card required.',
    keywords: 'NXTED AI signup, free AI career account, create resume builder account, free career coaching signup',
    canonical: '/signup',
    h1: 'Start Your AI-Powered Career Transformation — Free',
  },
  dashboard: {
    title: 'Career Dashboard — NXTED AI | Track Your Progress',
    description: 'Your AI career command center. Track skill progress, market readiness, career milestones, and job applications all in one dashboard.',
    keywords: 'AI career dashboard, career progress tracker, skill tracking AI, market readiness score',
    canonical: '/dashboard',
    h1: 'Your AI Career Dashboard',
  },
  assessment: {
    title: 'Free AI Skill Assessment Test — NXTED AI | Know Your Strengths',
    description: 'Take a free AI-powered skill assessment. Get instant skill scoring, gap analysis, market readiness score, and personalized improvement recommendations for your target career.',
    keywords: 'free AI skill assessment, skill gap analysis AI, career assessment test, AI skill test online, market readiness test, technical skill evaluation AI, career aptitude test AI',
    canonical: '/dashboard/assessment',
    h1: 'AI-Powered Skill Assessment — Discover Your Career Strengths',
  },
  careerPlan: {
    title: 'AI Career Plan Generator — Personalized Roadmap | NXTED AI',
    description: 'Get an AI-generated personalized career plan with visual timeline, milestones, proof-of-work projects, and adaptive recommendations. The fastest path to your dream job.',
    keywords: 'AI career plan, personalized career roadmap, career path generator AI, career milestones, proof of work projects, career transition plan AI',
    canonical: '/dashboard/career-plan',
    h1: 'Your Personalized AI Career Roadmap',
  },
  learning: {
    title: 'Adaptive AI Learning Path — Courses & Projects | NXTED AI',
    description: 'AI-powered adaptive learning paths that evolve with your progress. Get personalized course recommendations, hands-on projects, and skill-building modules for your target career.',
    keywords: 'adaptive learning path AI, personalized learning AI, AI course recommendations, skill building platform, career learning path, AI education platform',
    canonical: '/dashboard/learning',
    h1: 'Adaptive Learning Path — AI-Personalized Education',
  },
  resume: {
    title: 'Free AI Resume Builder — ATS Optimized Templates | NXTED AI',
    description: 'Build ATS-friendly resumes with AI in minutes. AI-powered resume writer, keyword optimization, job-specific tailoring, multiple templates, and instant PDF export. Free to start.',
    keywords: 'AI resume builder free, ATS friendly resume, AI resume writer, resume keyword optimizer, AI resume tailor, resume PDF export, ATS optimized resume templates, best AI resume builder 2026',
    canonical: '/dashboard/resume',
    h1: 'AI Resume Builder — Create ATS-Optimized Resumes in Minutes',
  },
  portfolio: {
    title: 'AI Portfolio Builder — Showcase Your Skills | NXTED AI',
    description: 'Build a professional portfolio with AI-verified projects and skill badges. Create a shareable portfolio page that proves your abilities to employers.',
    keywords: 'AI portfolio builder, project portfolio generator, skill portfolio, proof of skills, verified credentials portfolio, developer portfolio builder',
    canonical: '/dashboard/portfolio',
    h1: 'Portfolio Builder — Showcase AI-Verified Skills & Projects',
  },
  jobs: {
    title: 'AI Job Matching — Smart Job Recommendations | NXTED AI',
    description: 'AI-powered job matching that explains why you fit each role. Get match scores, improvement suggestions, and optional automated applications. Find your perfect career match.',
    keywords: 'AI job matching, smart job recommendations, job search AI, automated job applications, AI job fit score, career matching AI, AI apply to jobs, job application automation',
    canonical: '/dashboard/jobs',
    h1: 'AI Job Matching — Find Your Perfect Career Fit',
  },
  settings: {
    title: 'Account Settings — NXTED AI',
    description: 'Manage your NXTED AI account settings, subscription, AI coach preferences, and privacy controls.',
    keywords: 'NXTED AI settings, account management',
    canonical: '/dashboard/settings',
    h1: 'Account Settings',
  },
  careers: {
    title: 'Careers at NXTED AI — Join the AI Career Revolution | OFORO AI',
    description: 'Join the NXTED AI team at OFORO AI. Explore open positions in AI, engineering, design, and more. Help build the future of career development.',
    keywords: 'NXTED AI careers, OFORO AI jobs, AI career platform jobs, tech startup hiring',
    canonical: '/careers',
  },
  press: {
    title: 'Press & Media — NXTED AI by OFORO AI | Brand Assets & News',
    description: 'NXTED AI press resources, brand assets, and media contact information. Get the latest news about our AI-powered career development platform.',
    keywords: 'NXTED AI press, OFORO AI news, AI career platform media, brand assets',
    canonical: '/press',
  },
  contact: {
    title: 'Contact NXTED AI — Get in Touch | Support & Partnerships',
    description: 'Contact the NXTED AI team for support, partnerships, or general inquiries. We are here to help with your AI career development journey.',
    keywords: 'contact NXTED AI, NXTED AI support, OFORO AI contact, career platform help',
    canonical: '/contact',
  },
  privacy: {
    title: 'Privacy Policy — NXTED AI | How We Protect Your Data',
    description: 'NXTED AI privacy policy. Learn how we collect, use, and protect your personal and career data. GDPR compliant with full transparency.',
    keywords: 'NXTED AI privacy policy, career data privacy, GDPR privacy, data protection',
    canonical: '/privacy',
  },
  terms: {
    title: 'Terms of Service — NXTED AI | User Agreement',
    description: 'NXTED AI terms of service. Read our user agreement covering service usage, billing, intellectual property, and platform rules.',
    keywords: 'NXTED AI terms of service, user agreement, platform rules, subscription terms',
    canonical: '/terms',
  },
  gdpr: {
    title: 'GDPR Compliance — NXTED AI | Your Data Rights',
    description: 'NXTED AI GDPR compliance. Understand your data rights including access, rectification, erasure, portability, and objection under GDPR.',
    keywords: 'NXTED AI GDPR, data rights, GDPR compliance, data protection officer, right to erasure',
    canonical: '/gdpr',
  },
  // ─── Comparison Pages (High-Intent SEO) ──────────────
  compareHub: {
    title: 'NXTED AI vs Competitors — See How We Compare',
    description: 'Compare NXTED AI with Jobscan, Teal, Rezi, Kickresume, Careerflow, and Hiration. See why NXTED AI is the best all-in-one AI career platform.',
    keywords: 'NXTED AI alternatives, Jobscan alternative, Teal alternative, Rezi alternative, best AI resume builder comparison, AI career platform comparison 2026',
    canonical: '/compare',
  },
  compareJobscan: {
    title: 'NXTED AI vs Jobscan — The Better Jobscan Alternative (2026)',
    description: 'Looking for a Jobscan alternative? NXTED AI offers AI resume builder, ATS checker, career coaching, salary estimator, and job matching — all-in-one at $12/mo vs Jobscan $49.95/mo.',
    keywords: 'Jobscan alternative, NXTED AI vs Jobscan, Jobscan competitor, best ATS resume checker, AI resume builder vs Jobscan, cheaper Jobscan alternative 2026',
    canonical: '/compare/jobscan',
  },
  compareTeal: {
    title: 'NXTED AI vs Teal — The Better Teal Alternative (2026)',
    description: 'Looking for a Teal alternative? NXTED AI offers salary tools, skills assessment, portfolio builder, AI career coaching, and job matching that Teal lacks.',
    keywords: 'Teal alternative, Teal vs Jobscan, NXTED AI vs Teal, Teal resume builder alternative, Teal HQ competitor, best job tracker alternative 2026',
    canonical: '/compare/teal',
  },
  compareRezi: {
    title: 'NXTED AI vs Rezi — The Better Rezi Alternative (2026)',
    description: 'Looking for a Rezi alternative? NXTED AI offers AI career coaching, salary estimator, skills assessment, job matching, and portfolio builder that Rezi lacks.',
    keywords: 'Rezi alternative, Rezi vs Kickresume, NXTED AI vs Rezi, Rezi AI resume builder alternative, best AI resume builder 2026',
    canonical: '/compare/rezi',
  },
  compareAll: {
    title: 'Best AI Resume Builder 2026 — NXTED AI vs Jobscan vs Teal vs Rezi vs Kickresume',
    description: 'Comprehensive comparison of the best AI resume builders in 2026. NXTED AI vs Jobscan vs Teal vs Rezi vs Kickresume vs Careerflow vs Hiration — features, pricing, and ratings.',
    keywords: 'best AI resume builder 2026, AI resume builder comparison, Jobscan vs Teal vs Rezi, AI career platform comparison, Kickresume alternative, Careerflow alternative, Hiration alternative',
    canonical: '/compare/all',
  },
} as const;

// ─── Competitor Comparison Keywords (for PPC/SEO) ──────
export const COMPARISON_KEYWORDS = [
  'Jobscan alternative',
  'Teal alternative',
  'Teal vs Jobscan',
  'Rezi alternative',
  'Rezi vs Kickresume',
  'Kickresume alternative',
  'Careerflow alternative',
  'Hiration alternative',
  'best AI resume builder 2026',
  'best AI career platform 2026',
  'AI resume builder comparison',
  'Jobscan vs NXTED AI',
  'cheaper Jobscan alternative',
  'free AI resume builder alternative',
  'all in one career platform',
] as const;

// ─── Schema.org Structured Data Templates ──────────────
export const SCHEMA_ORG = {
  organization: {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'NXTED AI',
    alternateName: 'NXTED AI by OFORO AI',
    url: 'https://nxted.ai',
    logo: 'https://nxted.ai/assets/brand/logo.svg',
    description: 'AI-powered career operating system — resume builder, career coaching, skill assessment, and job matching.',
    parentOrganization: {
      '@type': 'Organization',
      name: 'OFORO AI',
      url: 'https://oforo.ai',
    },
    sameAs: [
      'https://twitter.com/nxtedai',
      'https://linkedin.com/company/nxtedai',
      'https://github.com/brijinchacko',
    ],
  },
  website: {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'NXTED AI',
    url: 'https://nxted.ai',
    description: 'AI career platform with resume builder, skill assessment, career coaching, and job matching',
    potentialAction: {
      '@type': 'SearchAction',
      target: 'https://nxted.ai/dashboard/jobs?q={search_term_string}',
      'query-input': 'required name=search_term_string',
    },
  },
  softwareApplication: {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'NXTED AI',
    applicationCategory: 'BusinessApplication',
    operatingSystem: 'Web',
    offers: [
      {
        '@type': 'Offer',
        name: 'Basic',
        price: '0',
        priceCurrency: 'USD',
        description: 'Free AI resume builder with limited assessments and AI credits',
      },
      {
        '@type': 'Offer',
        name: 'Pro',
        price: '19',
        priceCurrency: 'USD',
        description: 'Full AI career toolkit with unlimited resumes, job matching, and interview prep',
      },
      {
        '@type': 'Offer',
        name: 'Ultra',
        price: '49',
        priceCurrency: 'USD',
        description: 'Maximum automation with auto-apply, advanced analytics, and priority AI',
      },
    ],
    aggregateRating: {
      '@type': 'AggregateRating',
      ratingValue: '4.8',
      ratingCount: '2847',
      bestRating: '5',
    },
  },
  faqPage: (faqs: { question: string; answer: string }[]) => ({
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.answer,
      },
    })),
  }),
  breadcrumb: (items: { name: string; url: string }[]) => ({
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: item.name,
      item: item.url,
    })),
  }),
};
