export const COMMON_WORDS = new Set<string>([
  // Articles, prepositions, conjunctions, pronouns
  'the', 'a', 'an', 'in', 'on', 'at', 'for', 'with', 'and', 'or', 'but',
  'to', 'of', 'by', 'from', 'up', 'about', 'into', 'through', 'during',
  'before', 'after', 'above', 'below', 'between', 'under', 'over', 'out',
  'off', 'down', 'near', 'against', 'along', 'around', 'among', 'within',
  'without', 'across', 'behind', 'beyond', 'toward', 'towards', 'upon',
  'throughout', 'beside', 'besides', 'despite', 'except', 'since', 'until',
  'unless', 'although', 'though', 'while', 'whereas', 'whether', 'if',
  'then', 'than', 'that', 'this', 'these', 'those', 'which', 'who', 'whom',
  'whose', 'what', 'where', 'when', 'how', 'why', 'because', 'so', 'yet',
  'nor', 'not', 'no', 'yes', 'also', 'too', 'very', 'just', 'only', 'even',
  'still', 'already', 'always', 'never', 'often', 'sometimes', 'usually',
  'perhaps', 'maybe', 'however', 'therefore', 'thus', 'hence', 'moreover',
  'furthermore', 'nevertheless', 'nonetheless', 'meanwhile', 'otherwise',
  'instead', 'rather', 'either', 'neither', 'both', 'each', 'every', 'all',
  'any', 'some', 'few', 'many', 'much', 'more', 'most', 'other', 'another',
  'such', 'same', 'different', 'several', 'certain', 'various', 'own',
  'i', 'me', 'my', 'mine', 'myself', 'we', 'us', 'our', 'ours', 'ourselves',
  'you', 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his',
  'himself', 'she', 'her', 'hers', 'herself', 'it', 'its', 'itself',
  'they', 'them', 'their', 'theirs', 'themselves', 'here', 'there', 'now',
  'as', 'well', 'like', 'able', 'per',

  // Common verbs
  'be', 'is', 'am', 'are', 'was', 'were', 'been', 'being',
  'have', 'has', 'had', 'having',
  'do', 'does', 'did', 'doing', 'done',
  'will', 'would', 'shall', 'should', 'may', 'might', 'can', 'could',
  'must', 'need', 'ought',
  'say', 'said', 'says', 'saying',
  'go', 'goes', 'went', 'going', 'gone',
  'get', 'gets', 'got', 'getting', 'gotten',
  'make', 'makes', 'made', 'making',
  'know', 'knows', 'knew', 'known', 'knowing',
  'think', 'thinks', 'thought', 'thinking',
  'take', 'takes', 'took', 'taken', 'taking',
  'see', 'sees', 'saw', 'seen', 'seeing',
  'come', 'comes', 'came', 'coming',
  'want', 'wants', 'wanted', 'wanting',
  'look', 'looks', 'looked', 'looking',
  'use', 'uses', 'used', 'using',
  'find', 'finds', 'found', 'finding',
  'give', 'gives', 'gave', 'given', 'giving',
  'tell', 'tells', 'told', 'telling',
  'work', 'works', 'worked', 'working',
  'call', 'calls', 'called', 'calling',
  'try', 'tries', 'tried', 'trying',
  'ask', 'asks', 'asked', 'asking',
  'put', 'puts', 'putting',
  'keep', 'keeps', 'kept', 'keeping',
  'let', 'lets', 'letting',
  'begin', 'begins', 'began', 'begun', 'beginning',
  'show', 'shows', 'showed', 'shown', 'showing',
  'hear', 'hears', 'heard', 'hearing',
  'play', 'plays', 'played', 'playing',
  'run', 'runs', 'ran', 'running',
  'move', 'moves', 'moved', 'moving',
  'live', 'lives', 'lived', 'living',
  'believe', 'believes', 'believed', 'believing',
  'bring', 'brings', 'brought', 'bringing',
  'happen', 'happens', 'happened', 'happening',
  'write', 'writes', 'wrote', 'written', 'writing',
  'provide', 'provides', 'provided', 'providing',
  'sit', 'sits', 'sat', 'sitting',
  'stand', 'stands', 'stood', 'standing',
  'lose', 'loses', 'lost', 'losing',
  'pay', 'pays', 'paid', 'paying',
  'meet', 'meets', 'met', 'meeting',
  'include', 'includes', 'included', 'including',
  'continue', 'continues', 'continued', 'continuing',
  'set', 'sets', 'setting',
  'learn', 'learns', 'learned', 'learning',
  'change', 'changes', 'changed', 'changing',
  'lead', 'leads', 'led', 'leading',
  'understand', 'understands', 'understood', 'understanding',
  'watch', 'watches', 'watched', 'watching',
  'follow', 'follows', 'followed', 'following',
  'stop', 'stops', 'stopped', 'stopping',
  'create', 'creates', 'created', 'creating',
  'speak', 'speaks', 'spoke', 'spoken', 'speaking',
  'read', 'reads', 'reading',
  'allow', 'allows', 'allowed', 'allowing',
  'add', 'adds', 'added', 'adding',
  'spend', 'spends', 'spent', 'spending',
  'grow', 'grows', 'grew', 'grown', 'growing',
  'open', 'opens', 'opened', 'opening',
  'walk', 'walks', 'walked', 'walking',
  'win', 'wins', 'won', 'winning',
  'offer', 'offers', 'offered', 'offering',
  'remember', 'remembers', 'remembered', 'remembering',
  'love', 'loves', 'loved', 'loving',
  'consider', 'considers', 'considered', 'considering',
  'appear', 'appears', 'appeared', 'appearing',
  'buy', 'buys', 'bought', 'buying',
  'wait', 'waits', 'waited', 'waiting',
  'serve', 'serves', 'served', 'serving',
  'die', 'dies', 'died', 'dying',
  'send', 'sends', 'sent', 'sending',
  'expect', 'expects', 'expected', 'expecting',
  'build', 'builds', 'built', 'building',
  'stay', 'stays', 'stayed', 'staying',
  'fall', 'falls', 'fell', 'fallen', 'falling',
  'cut', 'cuts', 'cutting',
  'reach', 'reaches', 'reached', 'reaching',
  'kill', 'kills', 'killed', 'killing',
  'remain', 'remains', 'remained', 'remaining',
  'suggest', 'suggests', 'suggested', 'suggesting',
  'raise', 'raises', 'raised', 'raising',
  'pass', 'passes', 'passed', 'passing',
  'sell', 'sells', 'sold', 'selling',
  'require', 'requires', 'required', 'requiring',
  'report', 'reports', 'reported', 'reporting',
  'decide', 'decides', 'decided', 'deciding',
  'pull', 'pulls', 'pulled', 'pulling',
  'develop', 'develops', 'developed', 'developing',
  'manage', 'manages', 'managed', 'managing',
  'design', 'designs', 'designed', 'designing',
  'implement', 'implements', 'implemented', 'implementing',
  'support', 'supports', 'supported', 'supporting',
  'maintain', 'maintains', 'maintained', 'maintaining',
  'improve', 'improves', 'improved', 'improving',
  'achieve', 'achieves', 'achieved', 'achieving',
  'ensure', 'ensures', 'ensured', 'ensuring',
  'establish', 'establishes', 'established', 'establishing',
  'apply', 'applies', 'applied', 'applying',
  'receive', 'receives', 'received', 'receiving',
  'prepare', 'prepares', 'prepared', 'preparing',
  'produce', 'produces', 'produced', 'producing',
  'plan', 'plans', 'planned', 'planning',
  'drive', 'drives', 'drove', 'driven', 'driving',
  'deliver', 'delivers', 'delivered', 'delivering',
  'return', 'returns', 'returned', 'returning',
  'explain', 'explains', 'explained', 'explaining',
  'hope', 'hopes', 'hoped', 'hoping',
  'hold', 'holds', 'held', 'holding',
  'represent', 'represents', 'represented', 'representing',
  'join', 'joins', 'joined', 'joining',
  'perform', 'performs', 'performed', 'performing',
  'identify', 'identifies', 'identified', 'identifying',
  'define', 'defines', 'defined', 'defining',
  'handle', 'handles', 'handled', 'handling',
  'conduct', 'conducts', 'conducted', 'conducting',
  'focus', 'focuses', 'focused', 'focusing',
  'evaluate', 'evaluates', 'evaluated', 'evaluating',
  'monitor', 'monitors', 'monitored', 'monitoring',
  'coordinate', 'coordinates', 'coordinated', 'coordinating',
  'resolve', 'resolves', 'resolved', 'resolving',
  'communicate', 'communicates', 'communicated', 'communicating',
  'assist', 'assists', 'assisted', 'assisting',
  'review', 'reviews', 'reviewed', 'reviewing',
  'analyze', 'analyzes', 'analyzed', 'analyzing',
  'test', 'tests', 'tested', 'testing',
  'train', 'trains', 'trained', 'training',
  'hire', 'hires', 'hired', 'hiring',
  'engage', 'engages', 'engaged', 'engaging',
  'optimize', 'optimizes', 'optimized', 'optimizing',
  'execute', 'executes', 'executed', 'executing',
  'collaborate', 'collaborates', 'collaborated', 'collaborating',
  'facilitate', 'facilitates', 'facilitated', 'facilitating',
  'integrate', 'integrates', 'integrated', 'integrating',
  'generate', 'generates', 'generated', 'generating',
  'measure', 'measures', 'measured', 'measuring',
  'launch', 'launches', 'launched', 'launching',
  'operate', 'operates', 'operated', 'operating',
  'contribute', 'contributes', 'contributed', 'contributing',
  'negotiate', 'negotiates', 'negotiated', 'negotiating',
  'assess', 'assesses', 'assessed', 'assessing',
  'track', 'tracks', 'tracked', 'tracking',
  'determine', 'determines', 'determined', 'determining',
  'organize', 'organizes', 'organized', 'organizing',
  'respond', 'responds', 'responded', 'responding',
  'secure', 'secures', 'secured', 'securing',
  'present', 'presents', 'presented', 'presenting',
  'address', 'addresses', 'addressed', 'addressing',
  'publish', 'publishes', 'published', 'publishing',
  'document', 'documents', 'documented', 'documenting',
  'allocate', 'allocates', 'allocated', 'allocating',
  'research', 'researches', 'researched', 'researching',
  'complete', 'completes', 'completed', 'completing',
  'schedule', 'schedules', 'scheduled', 'scheduling',
  'enable', 'enables', 'enabled', 'enabling',
  'delegate', 'delegates', 'delegated', 'delegating',
  'mentor', 'mentors', 'mentored', 'mentoring',
  'inspect', 'inspects', 'inspected', 'inspecting',
  'advise', 'advises', 'advised', 'advising',
  'recruit', 'recruits', 'recruited', 'recruiting',
  'oversee', 'oversees', 'oversaw', 'overseeing',
  'advocate', 'advocates', 'advocated', 'advocating',
  'formulate', 'formulates', 'formulated', 'formulating',
  'innovate', 'innovates', 'innovated', 'innovating',
  'streamline', 'streamlines', 'streamlined', 'streamlining',
  'prioritize', 'prioritizes', 'prioritized', 'prioritizing',
  'automate', 'automates', 'automated', 'automating',
  'configure', 'configures', 'configured', 'configuring',
  'deploy', 'deploys', 'deployed', 'deploying',
  'debug', 'debugs', 'debugged', 'debugging',
  'compile', 'compiles', 'compiled', 'compiling',
  'migrate', 'migrates', 'migrated', 'migrating',
  'scale', 'scales', 'scaled', 'scaling',
  'troubleshoot', 'troubleshoots', 'troubleshooted', 'troubleshooting',
  'audit', 'audits', 'audited', 'auditing',
  'forecast', 'forecasts', 'forecasted', 'forecasting',
  'approve', 'approves', 'approved', 'approving',
  'draft', 'drafts', 'drafted', 'drafting',
  'negotiate', 'negotiated', 'negotiating',
  'comply', 'complies', 'complied', 'complying',

  // Common nouns
  'time', 'year', 'people', 'way', 'day', 'man', 'woman', 'child',
  'world', 'life', 'hand', 'part', 'place', 'case', 'week', 'company',
  'system', 'program', 'question', 'work', 'government', 'number', 'night',
  'point', 'home', 'water', 'room', 'mother', 'area', 'money', 'story',
  'fact', 'month', 'lot', 'right', 'study', 'book', 'eye', 'job', 'word',
  'business', 'issue', 'side', 'kind', 'head', 'house', 'service', 'friend',
  'father', 'power', 'hour', 'game', 'line', 'end', 'member', 'law', 'car',
  'city', 'community', 'name', 'president', 'team', 'minute', 'idea',
  'body', 'information', 'back', 'parent', 'face', 'others', 'level',
  'office', 'door', 'health', 'person', 'art', 'war', 'history', 'party',
  'result', 'reason', 'morning', 'group', 'center', 'age', 'course',
  'family', 'effect', 'student', 'class', 'state', 'country', 'problem',
  'school', 'market', 'form', 'food', 'care', 'society', 'activity',
  'thing', 'development', 'role', 'experience', 'education', 'effort',
  'music', 'force', 'sense', 'rate', 'position', 'cost', 'process',
  'practice', 'type', 'paper', 'value', 'term', 'color', 'policy',
  'period', 'action', 'mind', 'stage', 'interest', 'industry', 'event',
  'model', 'condition', 'record', 'field', 'order', 'chance', 'staff',
  'subject', 'rule', 'control', 'language', 'goal', 'view', 'decision',
  'evidence', 'choice', 'ground', 'future', 'site', 'demand', 'account',
  'need', 'source', 'series', 'price', 'standard', 'picture', 'thought',
  'material', 'structure', 'project', 'data', 'quality', 'resource',
  'access', 'product', 'response', 'performance', 'task', 'opportunity',
  'challenge', 'range', 'size', 'risk', 'benefit', 'solution', 'base',
  'step', 'list', 'impact', 'success', 'ability', 'knowledge', 'skill',
  'attention', 'space', 'space', 'degree', 'technology', 'method',
  'approach', 'network', 'culture', 'tool', 'issue', 'relationship',
  'unit', 'feature', 'board', 'requirement', 'content', 'section',
  'detail', 'framework', 'component', 'platform', 'function', 'direction',
  'context', 'factor', 'element', 'capacity', 'target', 'sample',
  'category', 'proposal', 'version', 'pattern', 'concept', 'reference',
  'outcome', 'procedure', 'objective', 'initiative', 'portfolio',
  'progress', 'status', 'scope', 'compliance', 'milestone', 'priority',
  'feedback', 'benchmark', 'deadline', 'agenda', 'summary', 'specification',
  'guideline', 'regulation', 'documentation', 'transition', 'collaboration',
  'partnership', 'presentation', 'recommendation', 'infrastructure',
  'implementation', 'evaluation', 'assessment', 'improvement',
  'responsibility', 'accountability', 'communication', 'commitment',
  'expectation', 'description', 'administration', 'organization',
  'instruction', 'observation', 'measurement', 'certification',
  'authorization', 'compensation', 'negotiation', 'investigation',

  // Job-related nouns
  'engineer', 'manager', 'developer', 'analyst', 'designer', 'coordinator',
  'director', 'supervisor', 'specialist', 'consultant', 'administrator',
  'architect', 'technician', 'associate', 'assistant', 'executive',
  'officer', 'representative', 'agent', 'advisor', 'planner', 'recruiter',
  'trainer', 'auditor', 'inspector', 'operator', 'programmer', 'scientist',
  'researcher', 'editor', 'writer', 'accountant', 'controller',
  'strategist', 'facilitator', 'practitioner', 'intern', 'apprentice',
  'contractor', 'freelancer', 'volunteer', 'candidate', 'applicant',
  'employer', 'employee', 'colleague', 'supervisor', 'subordinate',
  'workforce', 'personnel', 'department', 'division', 'branch', 'sector',
  'headquarters', 'subsidiary', 'corporation', 'enterprise', 'startup',
  'venture', 'firm', 'agency', 'bureau', 'institute', 'foundation',
  'marketing', 'sales', 'operations', 'finance', 'accounting',
  'engineering', 'manufacturing', 'logistics', 'procurement', 'purchasing',
  'warehouse', 'distribution', 'supply', 'chain', 'inventory',
  'production', 'assembly', 'maintenance', 'construction', 'installation',
  'consultation', 'advisory', 'auditing', 'compliance', 'governance',
  'regulation', 'inspection', 'certification', 'accreditation',
  'recruitment', 'onboarding', 'retention', 'attrition', 'turnover',
  'promotion', 'demotion', 'transfer', 'relocation', 'resignation',
  'termination', 'layoff', 'restructuring', 'downsizing', 'merger',
  'acquisition', 'divestiture', 'bankruptcy', 'liquidation',
  'salary', 'wage', 'bonus', 'commission', 'incentive', 'equity',
  'stock', 'option', 'pension', 'retirement', 'insurance', 'healthcare',
  'dental', 'vision', 'disability', 'leave', 'vacation', 'holiday',
  'overtime', 'shift', 'roster', 'schedule', 'timesheet',
  'interview', 'resume', 'portfolio', 'reference', 'background',
  'screening', 'assessment', 'evaluation', 'appraisal', 'review',
  'probation', 'tenure', 'seniority', 'qualification', 'credential',
  'license', 'permit', 'degree', 'diploma', 'certificate',
  'bachelor', 'master', 'doctorate', 'phd', 'mba',

  // Technology words
  'software', 'hardware', 'cloud', 'database', 'api', 'frontend',
  'backend', 'fullstack', 'devops', 'server', 'client', 'browser',
  'mobile', 'desktop', 'web', 'app', 'application', 'website',
  'code', 'coding', 'programming', 'algorithm', 'interface', 'user',
  'machine', 'learning', 'artificial', 'intelligence', 'neural',
  'automation', 'robot', 'robotics', 'digital', 'virtual', 'reality',
  'augmented', 'blockchain', 'crypto', 'cybersecurity', 'security',
  'encryption', 'firewall', 'malware', 'virus', 'phishing',
  'network', 'internet', 'intranet', 'ethernet', 'wifi', 'wireless',
  'bandwidth', 'latency', 'throughput', 'protocol', 'tcp', 'http',
  'https', 'html', 'css', 'javascript', 'typescript', 'python', 'java',
  'ruby', 'php', 'sql', 'nosql', 'mongodb', 'postgresql', 'mysql',
  'redis', 'elasticsearch', 'kafka', 'rabbitmq', 'docker', 'kubernetes',
  'aws', 'azure', 'gcp', 'terraform', 'ansible', 'jenkins', 'gitlab',
  'github', 'git', 'ci', 'cd', 'pipeline', 'deployment', 'release',
  'sprint', 'agile', 'scrum', 'kanban', 'waterfall', 'methodology',
  'microservice', 'microservices', 'monolith', 'architecture',
  'scalability', 'availability', 'reliability', 'redundancy',
  'backup', 'recovery', 'disaster', 'failover', 'load', 'balancer',
  'cache', 'caching', 'cdn', 'dns', 'ssl', 'tls', 'certificate',
  'authentication', 'authorization', 'oauth', 'saml', 'sso', 'ldap',
  'active', 'directory', 'identity', 'token', 'session', 'cookie',
  'payload', 'endpoint', 'webhook', 'rest', 'graphql', 'soap',
  'json', 'xml', 'yaml', 'csv', 'binary', 'ascii', 'unicode', 'utf',
  'sdk', 'cli', 'gui', 'ide', 'vscode', 'debug', 'log', 'logging',
  'error', 'exception', 'bug', 'fix', 'patch', 'update', 'upgrade',
  'migration', 'refactor', 'refactoring', 'optimization', 'profiling',
  'benchmark', 'unit', 'integration', 'regression', 'acceptance',
  'coverage', 'mock', 'stub', 'spy', 'fixture', 'assertion',
  'repository', 'branch', 'commit', 'merge', 'pull', 'push', 'clone',
  'fork', 'tag', 'version', 'semantic', 'changelog', 'readme',
  'linux', 'unix', 'windows', 'macos', 'ios', 'android',
  'react', 'angular', 'vue', 'svelte', 'next', 'nuxt', 'node',
  'express', 'django', 'flask', 'spring', 'rails', 'laravel',
  'webpack', 'vite', 'babel', 'eslint', 'prettier', 'npm', 'yarn',
  'package', 'module', 'library', 'framework', 'dependency',
  'responsive', 'accessibility', 'seo', 'analytics', 'dashboard',
  'widget', 'plugin', 'extension', 'addon', 'middleware',
  'container', 'orchestration', 'provisioning', 'monitoring',
  'alerting', 'observability', 'telemetry', 'metric', 'metrics',
  'tracing', 'span', 'trace', 'sampling',
  'schema', 'index', 'query', 'table', 'column', 'row', 'record',
  'transaction', 'migration', 'seed', 'orm', 'crud',
  'storage', 'file', 'object', 'blob', 'bucket', 'volume',
  'compute', 'instance', 'cluster', 'node', 'pod', 'namespace',
  'service', 'ingress', 'egress', 'gateway', 'proxy', 'reverse',
  'queue', 'message', 'event', 'stream', 'topic', 'subscription',
  'publish', 'subscribe', 'consumer', 'producer', 'broker',
  'serverless', 'lambda', 'edge', 'function', 'trigger',
  'variable', 'constant', 'parameter', 'argument', 'return',
  'class', 'method', 'property', 'attribute', 'constructor',
  'inheritance', 'polymorphism', 'encapsulation', 'abstraction',
  'pattern', 'singleton', 'factory', 'observer', 'strategy',
  'adapter', 'decorator', 'facade', 'iterator', 'command',
  'async', 'await', 'promise', 'callback', 'closure', 'scope',
  'thread', 'process', 'concurrency', 'parallel', 'mutex', 'lock',
  'deadlock', 'race', 'condition', 'semaphore', 'buffer',
  'stack', 'heap', 'memory', 'allocation', 'garbage', 'collection',
  'pointer', 'reference', 'value', 'type', 'string', 'number',
  'boolean', 'array', 'map', 'set', 'list', 'tree', 'graph', 'hash',
  'sort', 'search', 'traverse', 'iterate', 'recursive', 'recursion',
  'loop', 'iteration', 'conditional', 'switch', 'case', 'default',
  'break', 'continue', 'throw', 'catch', 'finally', 'try',
  'import', 'export', 'module', 'require', 'define',
  'static', 'dynamic', 'public', 'private', 'protected', 'internal',
  'abstract', 'interface', 'enum', 'struct', 'union', 'typedef',
  'generic', 'template', 'macro', 'annotation', 'metadata',
  'compiler', 'interpreter', 'runtime', 'bytecode', 'jit',
  'frontend', 'backend', 'middleware', 'fullstack',

  // Business and finance words
  'revenue', 'growth', 'strategy', 'budget', 'client', 'customer',
  'stakeholder', 'shareholder', 'investor', 'partner', 'vendor',
  'supplier', 'distributor', 'retailer', 'wholesaler', 'manufacturer',
  'profit', 'loss', 'margin', 'gross', 'net', 'overhead', 'expense',
  'expenditure', 'capital', 'asset', 'liability', 'debt', 'credit',
  'debit', 'balance', 'sheet', 'statement', 'income', 'cash', 'flow',
  'forecast', 'projection', 'estimate', 'variance', 'roi', 'kpi',
  'metric', 'indicator', 'dashboard', 'report', 'quarterly', 'annual',
  'fiscal', 'calendar', 'financial', 'monetary', 'economic', 'economy',
  'market', 'segment', 'niche', 'competitive', 'advantage', 'leverage',
  'synergy', 'alignment', 'transformation', 'disruption', 'innovation',
  'acquisition', 'retention', 'churn', 'lifetime', 'conversion', 'funnel',
  'pipeline', 'prospect', 'opportunity', 'deal', 'contract', 'agreement',
  'proposal', 'quote', 'invoice', 'payment', 'billing', 'subscription',
  'recurring', 'transaction', 'settlement', 'reconciliation',
  'brand', 'branding', 'awareness', 'reputation', 'perception',
  'positioning', 'differentiation', 'proposition', 'messaging',
  'campaign', 'promotion', 'advertising', 'publicity', 'outreach',
  'engagement', 'impression', 'click', 'lead', 'referral',
  'acquisition', 'lifecycle', 'journey', 'touchpoint', 'channel',
  'omnichannel', 'multichannel', 'retail', 'commerce', 'ecommerce',
  'marketplace', 'platform', 'ecosystem', 'supply', 'demand',
  'pricing', 'discount', 'coupon', 'rebate', 'markup', 'markdown',
  'wholesale', 'retail', 'msrp', 'cost', 'overhead', 'cogs',
  'procurement', 'sourcing', 'outsourcing', 'offshoring', 'nearshoring',
  'insourcing', 'rightsourcing', 'benchmarking', 'best', 'practice',
  'governance', 'risk', 'compliance', 'regulatory', 'legal', 'audit',
  'internal', 'external', 'third', 'party', 'due', 'diligence',
  'sustainability', 'esg', 'csr', 'diversity', 'equity', 'inclusion',
  'belonging', 'culture', 'values', 'mission', 'vision', 'purpose',

  // Common adjectives
  'good', 'great', 'new', 'old', 'big', 'small', 'long', 'short',
  'high', 'low', 'young', 'large', 'important', 'few', 'public',
  'bad', 'real', 'best', 'better', 'early', 'late', 'hard', 'major',
  'international', 'national', 'local', 'regional', 'global',
  'political', 'social', 'possible', 'personal', 'current', 'former',
  'full', 'special', 'general', 'free', 'clear', 'sure', 'strong',
  'human', 'common', 'medical', 'recent', 'whole', 'final', 'main',
  'available', 'specific', 'significant', 'similar', 'particular',
  'individual', 'professional', 'financial', 'traditional', 'natural',
  'physical', 'cultural', 'environmental', 'commercial', 'industrial',
  'critical', 'essential', 'effective', 'efficient', 'successful',
  'responsible', 'strategic', 'technical', 'operational', 'functional',
  'organizational', 'managerial', 'administrative', 'executive',
  'senior', 'junior', 'experienced', 'qualified', 'skilled',
  'capable', 'competent', 'proficient', 'knowledgeable', 'talented',
  'dedicated', 'committed', 'motivated', 'passionate', 'enthusiastic',
  'proactive', 'innovative', 'creative', 'analytical', 'logical',
  'systematic', 'methodical', 'thorough', 'meticulous', 'diligent',
  'reliable', 'dependable', 'trustworthy', 'honest', 'ethical',
  'flexible', 'adaptable', 'versatile', 'resourceful', 'resilient',
  'collaborative', 'cooperative', 'supportive', 'inclusive', 'diverse',
  'dynamic', 'energetic', 'positive', 'optimistic', 'constructive',
  'productive', 'profitable', 'sustainable', 'scalable', 'robust',
  'comprehensive', 'integrated', 'unified', 'consolidated', 'centralized',
  'decentralized', 'distributed', 'modular', 'agile', 'lean',
  'minimum', 'maximum', 'optimal', 'ideal', 'preferred', 'desired',
  'mandatory', 'optional', 'additional', 'supplementary', 'complementary',
  'primary', 'secondary', 'tertiary', 'initial', 'subsequent',
  'interim', 'temporary', 'permanent', 'ongoing', 'continuous',
  'regular', 'frequent', 'occasional', 'rare', 'unique', 'distinct',
  'separate', 'independent', 'dependent', 'mutual', 'reciprocal',
  'relevant', 'appropriate', 'suitable', 'adequate', 'sufficient',
  'necessary', 'crucial', 'vital', 'fundamental', 'basic',
  'advanced', 'intermediate', 'beginner', 'expert', 'master',
  'excellent', 'outstanding', 'exceptional', 'superior', 'premium',
  'standard', 'typical', 'normal', 'average', 'moderate',
  'competitive', 'attractive', 'compelling', 'engaging', 'interactive',
  'user', 'friendly', 'intuitive', 'seamless', 'smooth', 'efficient',
  'rapid', 'swift', 'immediate', 'instant', 'prompt', 'timely',
  'urgent', 'pressing', 'key', 'core', 'central', 'focal',
  'broad', 'wide', 'narrow', 'deep', 'shallow', 'extensive',
  'intensive', 'expansive', 'limited', 'restricted', 'bounded',
  'open', 'closed', 'transparent', 'opaque', 'visible', 'hidden',
  'explicit', 'implicit', 'direct', 'indirect', 'straight', 'forward',
  'complex', 'simple', 'complicated', 'sophisticated', 'elegant',
  'clean', 'neat', 'tidy', 'organized', 'structured', 'systematic',
  'complete', 'partial', 'total', 'overall', 'aggregate',
  'digital', 'analog', 'manual', 'automated', 'autonomous',
  'remote', 'onsite', 'hybrid', 'virtual', 'physical',
  'domestic', 'foreign', 'overseas', 'offshore', 'onshore',

  // Common adverbs
  'not', 'also', 'very', 'often', 'however', 'too', 'usually',
  'really', 'already', 'below', 'always', 'sometimes', 'together',
  'quite', 'easily', 'especially', 'carefully', 'completely',
  'widely', 'quickly', 'slowly', 'directly', 'currently', 'recently',
  'previously', 'originally', 'initially', 'subsequently', 'finally',
  'ultimately', 'eventually', 'immediately', 'gradually', 'increasingly',
  'significantly', 'substantially', 'considerably', 'approximately',
  'roughly', 'precisely', 'exactly', 'specifically', 'particularly',
  'primarily', 'mainly', 'largely', 'mostly', 'partly', 'partially',
  'fully', 'entirely', 'totally', 'absolutely', 'definitely',
  'certainly', 'clearly', 'obviously', 'apparently', 'evidently',
  'presumably', 'probably', 'possibly', 'potentially', 'likely',
  'effectively', 'efficiently', 'successfully', 'independently',
  'simultaneously', 'accordingly', 'consequently', 'alternatively',

  // Numbers and time
  'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight',
  'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen',
  'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty', 'thirty',
  'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety', 'hundred',
  'thousand', 'million', 'billion', 'first', 'second', 'third',
  'fourth', 'fifth', 'sixth', 'seventh', 'eighth', 'ninth', 'tenth',
  'half', 'quarter', 'double', 'triple', 'single', 'multiple',
  'today', 'tomorrow', 'yesterday', 'daily', 'weekly', 'monthly',
  'yearly', 'annually', 'biweekly', 'bimonthly', 'semi', 'bi',

  // Education and academia
  'university', 'college', 'school', 'academy', 'institute',
  'curriculum', 'syllabus', 'course', 'lecture', 'seminar',
  'workshop', 'conference', 'symposium', 'webinar', 'tutorial',
  'thesis', 'dissertation', 'publication', 'journal', 'article',
  'abstract', 'citation', 'bibliography', 'footnote', 'appendix',
  'grade', 'score', 'gpa', 'transcript', 'enrollment',
  'scholarship', 'fellowship', 'grant', 'funding', 'tuition',
  'professor', 'instructor', 'lecturer', 'teacher', 'tutor',
  'dean', 'provost', 'chancellor', 'registrar', 'counselor',

  // Healthcare and medical
  'patient', 'physician', 'nurse', 'surgeon', 'therapist',
  'pharmacist', 'dentist', 'psychiatrist', 'psychologist', 'radiologist',
  'diagnosis', 'treatment', 'therapy', 'surgery', 'medication',
  'prescription', 'dosage', 'symptom', 'condition', 'disease',
  'clinical', 'therapeutic', 'diagnostic', 'preventive', 'palliative',
  'hospital', 'clinic', 'laboratory', 'pharmacy', 'emergency',
  'ambulance', 'intensive', 'outpatient', 'inpatient', 'rehabilitation',
  'wellness', 'fitness', 'nutrition', 'diet', 'exercise',
  'mental', 'behavioral', 'cognitive', 'emotional', 'psychological',

  // Legal
  'attorney', 'lawyer', 'counsel', 'paralegal', 'solicitor',
  'barrister', 'judge', 'magistrate', 'arbitrator', 'mediator',
  'litigation', 'prosecution', 'defense', 'plaintiff', 'defendant',
  'verdict', 'judgment', 'settlement', 'appeal', 'motion',
  'statute', 'ordinance', 'regulation', 'amendment', 'provision',
  'clause', 'section', 'paragraph', 'subsection', 'article',
  'jurisdiction', 'court', 'tribunal', 'hearing', 'trial',
  'testimony', 'deposition', 'affidavit', 'subpoena', 'warrant',
  'patent', 'trademark', 'copyright', 'intellectual', 'property',

  // Communication and media
  'email', 'phone', 'text', 'chat', 'video', 'audio', 'media',
  'press', 'news', 'broadcast', 'podcast', 'blog', 'post', 'tweet',
  'social', 'platform', 'channel', 'audience', 'viewer', 'reader',
  'subscriber', 'follower', 'influencer', 'ambassador', 'spokesperson',
  'headline', 'caption', 'title', 'subtitle', 'description',
  'summary', 'overview', 'introduction', 'conclusion', 'body',
  'paragraph', 'sentence', 'phrase', 'word', 'letter', 'character',
  'font', 'format', 'layout', 'template', 'draft', 'edition',
  'copy', 'editing', 'proofreading', 'revision', 'translation',

  // Place and geography
  'country', 'state', 'city', 'town', 'village', 'district',
  'region', 'province', 'county', 'municipality', 'borough',
  'neighborhood', 'street', 'avenue', 'boulevard', 'highway',
  'building', 'floor', 'suite', 'office', 'campus', 'facility',
  'location', 'address', 'headquarters', 'branch', 'satellite',

  // Miscellaneous common words
  'thing', 'stuff', 'matter', 'item', 'piece', 'bit', 'part',
  'whole', 'total', 'amount', 'quantity', 'volume', 'mass', 'weight',
  'height', 'width', 'length', 'depth', 'distance', 'speed',
  'rate', 'ratio', 'percentage', 'fraction', 'proportion', 'share',
  'majority', 'minority', 'remainder', 'surplus', 'deficit', 'gap',
  'difference', 'comparison', 'contrast', 'similarity', 'distinction',
  'advantage', 'disadvantage', 'strength', 'weakness', 'threat',
  'opportunity', 'challenge', 'obstacle', 'barrier', 'constraint',
  'limitation', 'restriction', 'boundary', 'border', 'edge', 'margin',
  'center', 'middle', 'top', 'bottom', 'left', 'right', 'front',
  'rear', 'side', 'corner', 'angle', 'curve', 'circle', 'square',
  'triangle', 'rectangle', 'shape', 'form', 'figure', 'image',
  'picture', 'photo', 'photograph', 'illustration', 'diagram',
  'chart', 'graph', 'table', 'matrix', 'grid', 'map', 'plan',
  'blueprint', 'sketch', 'drawing', 'render', 'prototype', 'mockup',
  'wireframe', 'storyboard', 'flowchart', 'mindmap', 'roadmap',
  'timeline', 'calendar', 'schedule', 'planner', 'organizer',
  'note', 'memo', 'notification', 'alert', 'warning', 'notice',
  'announcement', 'bulletin', 'circular', 'newsletter', 'digest',
  'release', 'update', 'patch', 'version', 'revision', 'edition',
  'copy', 'duplicate', 'replica', 'clone', 'backup', 'archive',
  'original', 'authentic', 'genuine', 'legitimate', 'valid',
  'invalid', 'expired', 'outdated', 'obsolete', 'deprecated',
  'current', 'latest', 'newest', 'updated', 'revised', 'amended',
  'effective', 'applicable', 'relevant', 'pertinent', 'material',
  'substantial', 'significant', 'meaningful', 'noteworthy', 'remarkable',
  'plus', 'minus', 'equals', 'greater', 'lesser', 'equal',
  'above', 'below', 'beyond', 'within', 'outside', 'inside',
  'level', 'tier', 'grade', 'rank', 'rating', 'classification',
  'category', 'subcategory', 'group', 'subgroup', 'cluster',
  'segment', 'subset', 'superset', 'intersection', 'union',
]);
