'use client';

import { motion } from 'framer-motion';
import {
  FileCheck, Info, UserPlus, Users, CreditCard, Coins,
  Bot, Copyright, ShieldAlert, LogOut, Gavel, RefreshCw,
} from 'lucide-react';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';

const sections = [
  {
    icon: Info,
    title: 'Service Description',
    content: [
      { text: 'jobTED AI provides AI-powered career development tools including skill assessments, personalized career planning, resume building, portfolio creation, job matching, and interview preparation.' },
      { text: 'The platform is provided "as is" and we continuously improve features.' },
      { text: 'Some features require a paid subscription (Starter, Pro, or Ultra plan).' },
      { text: 'Free tier includes limited access to all core features.' },
    ],
  },
  {
    icon: UserPlus,
    title: 'Account Registration',
    content: [
      { text: 'You must be at least 16 years old to create an account.' },
      { text: 'You must provide accurate and complete registration information.' },
      { text: 'You are responsible for maintaining the confidentiality of your account credentials.' },
      { text: 'One account per person; shared accounts are not permitted.' },
      { text: 'You must notify us immediately of any unauthorized account access.' },
    ],
  },
  {
    icon: Users,
    title: 'User Responsibilities',
    content: [
      { text: 'Provide accurate information in assessments, resumes, and profiles.' },
      { text: 'Maintain the security of your account credentials.' },
      { text: 'Use the platform in compliance with applicable laws and regulations.' },
      { text: 'Do not use automated tools to access the platform without permission.' },
      { text: 'Do not attempt to reverse-engineer, decompile, or extract source code from the platform.' },
      { text: 'Do not upload malicious content or attempt to disrupt platform services.' },
    ],
  },
  {
    icon: CreditCard,
    title: 'Subscription & Billing',
    content: [
      { heading: 'Free plan', text: 'Basic access at no cost, forever.' },
      { heading: 'Paid plans (Starter $10/mo, Pro $24/mo, Ultra $49/mo)', text: 'Billed monthly or yearly as selected.' },
      { text: 'Yearly billing saves 20% compared to monthly.' },
      { text: 'You can upgrade, downgrade, or cancel anytime from Settings.' },
      { text: 'Refunds available within 14 days of initial purchase.' },
      { text: 'Plan changes take effect immediately with prorated billing.' },
      { text: 'Failed payments may result in temporary service suspension.' },
    ],
  },
  {
    icon: Coins,
    title: 'AI Credits & Usage',
    content: [
      { text: 'AI features consume credits based on complexity (assessments, career plans, interview prep, resume AI enhancements).' },
      { text: 'Free plan includes 10 AI credits per month.' },
      { text: 'Paid plans include higher credit allocations (see Pricing page).' },
      { text: 'Additional credit packs can be purchased separately.' },
      { text: 'Unused credits do not roll over between billing periods.' },
      { text: 'Credits are non-transferable and non-refundable.' },
    ],
  },
  {
    icon: Bot,
    title: 'Automation Disclaimer',
    content: [
      { text: 'Ultra plan automation features (auto-apply) act on your behalf on third-party job platforms.' },
      { text: 'You are responsible for reviewing and configuring automation settings.' },
      { text: 'You must maintain compliance with third-party job platform terms of service.' },
      { text: 'jobTED AI provides career tools and does not guarantee employment outcomes.' },
      { text: 'We are not liable for actions taken by automated systems on external platforms.' },
    ],
  },
  {
    icon: Copyright,
    title: 'Intellectual Property',
    content: [
      { heading: 'Your content', text: 'You retain full ownership of all content you create (resumes, portfolios, cover letters, assessment responses).' },
      { heading: 'Our platform', text: 'jobTED AI, OFORO AI, and all platform code, AI models, algorithms, and proprietary features are our intellectual property.' },
      { heading: 'AI-generated content', text: 'Content generated by AI based on your input belongs to you.' },
      { heading: 'Feedback', text: 'Any suggestions or feedback you provide may be used to improve the platform without obligation.' },
    ],
  },
  {
    icon: ShieldAlert,
    title: 'Limitation of Liability',
    content: [
      { text: 'The platform is provided "as is" without warranties of any kind.' },
      { text: 'We do not guarantee the accuracy of AI-generated content or career recommendations.' },
      { text: 'We are not liable for indirect, incidental, or consequential damages.' },
      { text: 'Our total liability is limited to the amount you paid us in the 12 months preceding the claim.' },
      { text: 'We are not responsible for third-party services (Stripe, Google, job platforms).' },
    ],
  },
  {
    icon: LogOut,
    title: 'Termination',
    content: [
      { text: 'You may terminate your account at any time from Settings.' },
      { text: 'We may suspend or terminate accounts that violate these terms.' },
      { text: 'Upon termination, your data will be deleted within 30 days (except as required by law).' },
      { text: 'Sections on intellectual property, limitation of liability, and governing law survive termination.' },
    ],
  },
  {
    icon: Gavel,
    title: 'Governing Law',
    content: [
      { text: 'These terms are governed by the laws of the United States.' },
      { text: 'Disputes shall be resolved through binding arbitration.' },
      { text: 'You agree to resolve disputes individually, not as part of a class action.' },
      { text: 'Contact: legal@oforo.ai for legal inquiries.' },
    ],
  },
  {
    icon: RefreshCw,
    title: 'Changes to Terms',
    content: [
      { text: 'We may update these terms periodically.' },
      { text: 'Significant changes will be communicated via email and in-app notification at least 30 days in advance.' },
      { text: 'Continued use after changes constitutes acceptance.' },
      { text: 'If you disagree with changes, you may terminate your account.' },
    ],
  },
];

export default function TermsPageClient() {
  return (
    <div className="min-h-screen">
      <Navbar />

      <section className="pt-32 pb-24 relative overflow-hidden">
        <div className="absolute inset-0 bg-grid opacity-30" />

        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Hero */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center mb-16"
          >
            <FileCheck className="w-12 h-12 text-neon-green mx-auto mb-4" />
            <h1 className="text-4xl sm:text-5xl font-extrabold mb-4">
              Terms of <span className="gradient-text">Service</span>
            </h1>
            <p className="text-white/40 max-w-xl mx-auto mb-4">
              The rules and guidelines that govern your use of jobTED AI.
            </p>
            <span className="inline-block text-xs text-white/50 bg-white/5 border border-white/10 rounded-full px-4 py-1.5">
              Last updated: March 1, 2026
            </span>
          </motion.div>

          {/* Content Cards */}
          <div className="space-y-8">
            {sections.map((section, i) => (
              <motion.div
                key={section.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.05 }}
                className="card"
              >
                <div className="flex items-center gap-3 mb-4">
                  <section.icon className="w-6 h-6 text-neon-green flex-shrink-0" />
                  <h2 className="text-xl font-bold">{section.title}</h2>
                </div>
                <div className="space-y-4 text-sm text-white/50 leading-relaxed">
                  {section.content.map((item, j) => (
                    <p key={j}>
                      {'heading' in item && item.heading && (
                        <span className="text-white font-semibold">{item.heading}: </span>
                      )}
                      {item.text}
                    </p>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
