/**
 * Agent Pipeline Orchestrator
 * Coordinates all agents based on user's plan and configuration
 */
import { prisma } from '@/lib/db/prisma';
import { isAgentAvailable } from './permissions';
import { runScout } from './scout';
import { analyzeResumeForJob } from './forge';
import { applyToJob } from './archer';
import { prepareInterview } from './atlas';
import { analyzeSkillGaps } from './sage';
import { reviewApplication } from './sentinel';
import { aiChatWithFallback } from '@/lib/ai/openrouter';

interface PipelineConfig {
  userId: string;
  plan: 'BASIC' | 'STARTER' | 'PRO' | 'ULTRA';
}

interface PipelineResult {
  runId: string;
  status: 'completed' | 'failed' | 'partial';
  jobsFound: number;
  jobsApplied: number;
  jobsSkipped: number;
  creditsUsed: number;
  summary: string;
}

export async function runAgentPipeline(config: PipelineConfig): Promise<PipelineResult> {
  const { userId, plan } = config;

  // Get user's auto-apply config
  const autoConfig = await prisma.autoApplyConfig.findUnique({ where: { userId } });
  if (!autoConfig || !autoConfig.enabled) {
    throw new Error('Auto-apply is not configured or disabled');
  }

  // Check for finalized resume
  const resume = autoConfig.resumeId
    ? await prisma.resume.findUnique({ where: { id: autoConfig.resumeId } })
    : await prisma.resume.findFirst({ where: { userId, isFinalized: true }, orderBy: { updatedAt: 'desc' } });

  if (!resume || !resume.isFinalized) {
    throw new Error('No finalized resume found. Please finalize your resume first.');
  }

  // Check credits
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { aiCreditsUsed: true, aiCreditsLimit: true, plan: true },
  });
  if (!user) throw new Error('User not found');

  const hasCredits = user.aiCreditsLimit < 0 || user.aiCreditsUsed < user.aiCreditsLimit;
  if (!hasCredits) {
    throw new Error('No AI credits remaining. Please upgrade your plan or purchase credits.');
  }

  const resumeContent = resume.content as any;
  const targetRoles = (autoConfig.targetRoles as string[]) || [];
  const targetLocations = (autoConfig.targetLocations as string[]) || [];
  const excludeCompanies = (autoConfig.excludeCompanies as string[]) || [];
  const excludeKeywords = (autoConfig.excludeKeywords as string[]) || [];

  // Create the run record
  const run = await prisma.autoApplyRun.create({
    data: { userId, status: 'running' },
  });

  let jobsFound = 0;
  let jobsApplied = 0;
  let jobsSkipped = 0;
  let creditsUsed = 0;

  try {
    // ── Step 1: Scout discovers jobs (STARTER+) ──
    let discoveredJobs: any[] = [];
    if (isAgentAvailable('scout', plan)) {
      const scoutResult = await runScout({
        userId,
        targetRoles,
        targetLocations,
        preferRemote: autoConfig.preferRemote,
        minMatchScore: autoConfig.minMatchScore,
        excludeCompanies,
        excludeKeywords,
        limit: 30,
      });
      discoveredJobs = scoutResult.jobs;
      jobsFound = scoutResult.totalFound;
    }

    if (discoveredJobs.length === 0) {
      await prisma.autoApplyRun.update({
        where: { id: run.id },
        data: { status: 'completed', jobsFound: 0, jobsApplied: 0, jobsSkipped: 0, creditsUsed: 0, completedAt: new Date(), summary: 'No matching jobs found in this run.' },
      });
      return { runId: run.id, status: 'completed', jobsFound: 0, jobsApplied: 0, jobsSkipped: 0, creditsUsed: 0, summary: 'No matching jobs found.' };
    }

    // Limit to maxAppliesPerRun
    const jobsToProcess = discoveredJobs.slice(0, autoConfig.maxAppliesPerRun);

    // ── Step 2: Forge optimizes resume for top matches (STARTER+) ──
    if (isAgentAvailable('forge', plan)) {
      for (const job of jobsToProcess.slice(0, 3)) { // Optimize for top 3
        try {
          await analyzeResumeForJob(userId, resumeContent, job.title, job.description, job.company);
        } catch {}
      }
    }

    // ── Step 3: For each job, generate cover letter + apply (PRO+) ──
    if (isAgentAvailable('archer', plan)) {
      for (const job of jobsToProcess) {
        // Check credits before each application
        const currentUser = await prisma.user.findUnique({ where: { id: userId }, select: { aiCreditsUsed: true, aiCreditsLimit: true } });
        if (currentUser && currentUser.aiCreditsLimit >= 0 && currentUser.aiCreditsUsed >= currentUser.aiCreditsLimit) {
          break; // Out of credits
        }

        try {
          // Sentinel review if available (ULTRA)
          let approved = true;
          if (isAgentAvailable('sentinel', plan)) {
            const review = await reviewApplication(userId, {
              jobTitle: job.title,
              company: job.company,
              jobDescription: job.description,
              coverLetter: '', // Will be generated by Archer
              resumeSummary: resumeContent.summary || '',
              candidateSkills: resumeContent.skills || [],
            });
            approved = review.approved;
          }

          if (!approved) {
            jobsSkipped++;
            continue;
          }

          const result = await applyToJob(userId, job, resumeContent, run.id);
          if (result.success) {
            jobsApplied++;
            creditsUsed++;
            // Deduct credit
            await prisma.user.update({ where: { id: userId }, data: { aiCreditsUsed: { increment: 1 } } });
          } else {
            jobsSkipped++;
          }
        } catch {
          jobsSkipped++;
        }
      }
    } else {
      // STARTER plan — just discover and show, don't apply
      jobsSkipped = jobsToProcess.length;
    }

    // ── Step 4: Atlas prepares interview questions for applied jobs (PRO+) ──
    if (isAgentAvailable('atlas', plan) && jobsApplied > 0) {
      const appliedJobs = jobsToProcess.slice(0, Math.min(3, jobsApplied));
      for (const job of appliedJobs) {
        try {
          await prepareInterview(userId, job.title, job.company, job.description, resumeContent.skills || []);
        } catch {}
      }
    }

    // ── Step 5: Sage identifies skill gaps (ULTRA) ──
    if (isAgentAvailable('sage', plan)) {
      try {
        const jds = jobsToProcess.slice(0, 3).map((j: any) => j.description);
        await analyzeSkillGaps(userId, resumeContent.skills || [], targetRoles[0] || '', jds);
      } catch {}
    }

    // ── Generate run summary ──
    let summary = `Found ${jobsFound} jobs`;
    if (jobsApplied > 0) summary += `, applied to ${jobsApplied}`;
    if (jobsSkipped > 0) summary += `, skipped ${jobsSkipped}`;
    if (creditsUsed > 0) summary += `. Used ${creditsUsed} credits.`;

    // Try AI summary
    try {
      const aiSummary = await aiChatWithFallback({ messages: [
        { role: 'system', content: 'You are Cortex, the AI coordinator. Write a brief, friendly 1-2 sentence summary of what your agent team accomplished. Use first person plural (we/our team). Be specific with numbers.' },
        { role: 'user', content: `Jobs found: ${jobsFound}, Applied: ${jobsApplied}, Skipped: ${jobsSkipped}, Credits used: ${creditsUsed}, Top companies: ${jobsToProcess.slice(0, 3).map((j: any) => j.company).join(', ')}` },
      ] }, 'free');
      summary = aiSummary.trim();
    } catch {}

    // Update run record
    await prisma.autoApplyRun.update({
      where: { id: run.id },
      data: { status: 'completed', jobsFound, jobsApplied, jobsSkipped, creditsUsed, summary, completedAt: new Date(), details: { processedJobs: jobsToProcess.map((j: any) => ({ title: j.title, company: j.company, score: j.matchScore })) } },
    });

    // Update config lastRunAt
    await prisma.autoApplyConfig.update({ where: { userId }, data: { lastRunAt: new Date() } });

    return { runId: run.id, status: 'completed', jobsFound, jobsApplied, jobsSkipped, creditsUsed, summary };
  } catch (err) {
    console.error('[Orchestrator] Pipeline error:', err);
    await prisma.autoApplyRun.update({
      where: { id: run.id },
      data: { status: 'failed', jobsFound, jobsApplied, jobsSkipped, creditsUsed, completedAt: new Date(), summary: `Pipeline failed: ${(err as Error).message}` },
    });
    return { runId: run.id, status: 'failed', jobsFound, jobsApplied, jobsSkipped, creditsUsed, summary: `Pipeline failed: ${(err as Error).message}` };
  }
}
